import { z } from 'zod'

// Pulled from https://github.com/freeall/currency-codes/blob/master/data.js
const currencies = [
	{
		code: 'AED',
		number: '784',
		digits: 2,
		currency: 'UAE Dirham',
		countries: ['ARE'],
	},
	{
		code: 'AFN',
		number: '971',
		digits: 2,
		currency: 'Afghani',
		countries: ['AFG'],
	},
	{
		code: 'ALL',
		number: '008',
		digits: 2,
		currency: 'Lek',
		countries: ['ALB'],
	},
	{
		code: 'AMD',
		number: '051',
		digits: 2,
		currency: 'Armenian Dram',
		countries: ['ARM'],
	},
	{
		code: 'ANG',
		number: '532',
		digits: 2,
		currency: 'Netherlands Antillean Guilder',
		countries: ['CUW', 'SXM'],
	},
	{
		code: 'AOA',
		number: '973',
		digits: 2,
		currency: 'Kwanza',
		countries: ['AGO'],
	},
	{
		code: 'ARS',
		number: '032',
		digits: 2,
		currency: 'Argentine Peso',
		countries: ['ARG'],
	},
	{
		code: 'AUD',
		number: '036',
		digits: 2,
		currency: 'Australian Dollar',
		countries: ['AUS', 'CXR', 'CCK', 'HMD', 'KIR', 'NRU', 'NFK', 'TUV'],
	},
	{
		code: 'AWG',
		number: '533',
		digits: 2,
		currency: 'Aruban Florin',
		countries: ['ABW'],
	},
	{
		code: 'AZN',
		number: '944',
		digits: 2,
		currency: 'Azerbaijan Manat',
		countries: ['AZE'],
	},
	{
		code: 'BAM',
		number: '977',
		digits: 2,
		currency: 'Convertible Mark',
		countries: ['BIH'],
	},
	{
		code: 'BBD',
		number: '052',
		digits: 2,
		currency: 'Barbados Dollar',
		countries: ['BRB'],
	},
	{
		code: 'BDT',
		number: '050',
		digits: 2,
		currency: 'Taka',
		countries: ['BGD'],
	},
	{
		code: 'BGN',
		number: '975',
		digits: 2,
		currency: 'Bulgarian Lev',
		countries: ['BGR'],
	},
	{
		code: 'BHD',
		number: '048',
		digits: 3,
		currency: 'Bahraini Dinar',
		countries: ['BHR'],
	},
	{
		code: 'BIF',
		number: '108',
		digits: 0,
		currency: 'Burundi Franc',
		countries: ['BDI'],
	},
	{
		code: 'BMD',
		number: '060',
		digits: 2,
		currency: 'Bermudian Dollar',
		countries: ['BMU'],
	},
	{
		code: 'BND',
		number: '096',
		digits: 2,
		currency: 'Brunei Dollar',
		countries: ['BRN'],
	},
	{
		code: 'BOB',
		number: '068',
		digits: 2,
		currency: 'Boliviano',
		countries: ['BOL'],
	},
	{
		code: 'BOV',
		number: '984',
		digits: 2,
		currency: 'Mvdol',
		countries: ['BOL'],
	},
	{
		code: 'BRL',
		number: '986',
		digits: 2,
		currency: 'Brazilian Real',
		countries: ['BRA'],
	},
	{
		code: 'BSD',
		number: '044',
		digits: 2,
		currency: 'Bahamian Dollar',
		countries: ['BHS'],
	},
	{
		code: 'BTN',
		number: '064',
		digits: 2,
		currency: 'Ngultrum',
		countries: ['BTN'],
	},
	{
		code: 'BWP',
		number: '072',
		digits: 2,
		currency: 'Pula',
		countries: ['BWA'],
	},
	{
		code: 'BYN',
		number: '933',
		digits: 2,
		currency: 'Belarusian Ruble',
		countries: ['BLR'],
	},
	{
		code: 'BZD',
		number: '084',
		digits: 2,
		currency: 'Belize Dollar',
		countries: ['BLZ'],
	},
	{
		code: 'CAD',
		number: '124',
		digits: 2,
		currency: 'Canadian Dollar',
		countries: ['CAN'],
	},
	{
		code: 'CDF',
		number: '976',
		digits: 2,
		currency: 'Congolese Franc',
		countries: ['COD'],
	},
	{
		code: 'CHE',
		number: '947',
		digits: 2,
		currency: 'WIR Euro',
		countries: ['CHE'],
	},
	{
		code: 'CHF',
		number: '756',
		digits: 2,
		currency: 'Swiss Franc',
		countries: ['CHE', 'LIE'],
	},
	{
		code: 'CHW',
		number: '948',
		digits: 2,
		currency: 'WIR Franc',
		countries: ['CHE'],
	},
	{
		code: 'CLF',
		number: '990',
		digits: 4,
		currency: 'Unidad de Fomento',
		countries: ['CHL'],
	},
	{
		code: 'CLP',
		number: '152',
		digits: 0,
		currency: 'Chilean Peso',
		countries: ['CHL'],
	},
	{
		code: 'CNY',
		number: '156',
		digits: 2,
		currency: 'Yuan Renminbi',
		countries: ['CHN'],
	},
	{
		code: 'COP',
		number: '170',
		digits: 2,
		currency: 'Colombian Peso',
		countries: ['COL'],
	},
	{
		code: 'COU',
		number: '970',
		digits: 2,
		currency: 'Unidad de Valor Real',
		countries: ['COL'],
	},
	{
		code: 'CRC',
		number: '188',
		digits: 2,
		currency: 'Costa Rican Colon',
		countries: ['CRI'],
	},
	{
		code: 'CUC',
		number: '931',
		digits: 2,
		currency: 'Peso Convertible',
		countries: ['CUB'],
	},
	{
		code: 'CUP',
		number: '192',
		digits: 2,
		currency: 'Cuban Peso',
		countries: ['CUB'],
	},
	{
		code: 'CVE',
		number: '132',
		digits: 2,
		currency: 'Cabo Verde Escudo',
		countries: ['CPV'],
	},
	{
		code: 'CZK',
		number: '203',
		digits: 2,
		currency: 'Czech Koruna',
		countries: ['CZE'],
	},
	{
		code: 'DJF',
		number: '262',
		digits: 0,
		currency: 'Djibouti Franc',
		countries: ['DJI'],
	},
	{
		code: 'DKK',
		number: '208',
		digits: 2,
		currency: 'Danish Krone',
		countries: ['DNK', 'FRO', 'GRL'],
	},
	{
		code: 'DOP',
		number: '214',
		digits: 2,
		currency: 'Dominican Peso',
		countries: ['DOM'],
	},
	{
		code: 'DZD',
		number: '012',
		digits: 2,
		currency: 'Algerian Dinar',
		countries: ['DZA'],
	},
	{
		code: 'EGP',
		number: '818',
		digits: 2,
		currency: 'Egyptian Pound',
		countries: ['EGY'],
	},
	{
		code: 'ERN',
		number: '232',
		digits: 2,
		currency: 'Nakfa',
		countries: ['ERI'],
	},
	{
		code: 'ETB',
		number: '230',
		digits: 2,
		currency: 'Ethiopian Birr',
		countries: ['ETH'],
	},
	{
		code: 'EUR',
		number: '978',
		digits: 2,
		currency: 'Euro',
		countries: [
			'ALA',
			'AND',
			'AUT',
			'BEL',
			'HRV',
			'CYP',
			'EST',
			'FIN',
			'FRA',
			'GUF',
			'ATF',
			'DEU',
			'GRC',
			'GLP',
			'VAT',
			'IRL',
			'ITA',
			'LVA',
			'LTU',
			'LUX',
			'MLT',
			'MTQ',
			'MYT',
			'MCO',
			'MNE',
			'NLD',
			'PRT',
			'REU',
			'BLM',
			'MAF',
			'SPM',
			'SMR',
			'SVK',
			'SVN',
			'ESP',
		],
	},
	{
		code: 'FJD',
		number: '242',
		digits: 2,
		currency: 'Fiji Dollar',
		countries: ['FJI'],
	},
	{
		code: 'FKP',
		number: '238',
		digits: 2,
		currency: 'Falkland Islands Pound',
		countries: ['FLK'],
	},
	{
		code: 'GBP',
		number: '826',
		digits: 2,
		currency: 'Pound Sterling',
		countries: ['GGY', 'IMN', 'JEY', 'GBR'],
	},
	{
		code: 'GEL',
		number: '981',
		digits: 2,
		currency: 'Lari',
		countries: ['GEO'],
	},
	{
		code: 'GHS',
		number: '936',
		digits: 2,
		currency: 'Ghana Cedi',
		countries: ['GHA'],
	},
	{
		code: 'GIP',
		number: '292',
		digits: 2,
		currency: 'Gibraltar Pound',
		countries: ['GIB'],
	},
	{
		code: 'GMD',
		number: '270',
		digits: 2,
		currency: 'Dalasi',
		countries: ['GMB'],
	},
	{
		code: 'GNF',
		number: '324',
		digits: 0,
		currency: 'Guinean Franc',
		countries: ['GIN'],
	},
	{
		code: 'GTQ',
		number: '320',
		digits: 2,
		currency: 'Quetzal',
		countries: ['GTM'],
	},
	{
		code: 'GYD',
		number: '328',
		digits: 2,
		currency: 'Guyana Dollar',
		countries: ['GUY'],
	},
	{
		code: 'HKD',
		number: '344',
		digits: 2,
		currency: 'Hong Kong Dollar',
		countries: ['HKG'],
	},
	{
		code: 'HNL',
		number: '340',
		digits: 2,
		currency: 'Lempira',
		countries: ['HND'],
	},
	{
		code: 'HTG',
		number: '332',
		digits: 2,
		currency: 'Gourde',
		countries: ['HTI'],
	},
	{
		code: 'HUF',
		number: '348',
		digits: 2,
		currency: 'Forint',
		countries: ['HUN'],
	},
	{
		code: 'IDR',
		number: '360',
		digits: 2,
		currency: 'Rupiah',
		countries: ['IDN'],
	},
	{
		code: 'ILS',
		number: '376',
		digits: 2,
		currency: 'New Israeli Sheqel',
		countries: ['ISR'],
	},
	{
		code: 'INR',
		number: '356',
		digits: 2,
		currency: 'Indian Rupee',
		countries: ['BTN', 'IND'],
	},
	{
		code: 'IQD',
		number: '368',
		digits: 3,
		currency: 'Iraqi Dinar',
		countries: ['IRQ'],
	},
	{
		code: 'IRR',
		number: '364',
		digits: 2,
		currency: 'Iranian Rial',
		countries: ['IRN'],
	},
	{
		code: 'ISK',
		number: '352',
		digits: 0,
		currency: 'Iceland Krona',
		countries: ['ISL'],
	},
	{
		code: 'JMD',
		number: '388',
		digits: 2,
		currency: 'Jamaican Dollar',
		countries: ['JAM'],
	},
	{
		code: 'JOD',
		number: '400',
		digits: 3,
		currency: 'Jordanian Dinar',
		countries: ['JOR'],
	},
	{
		code: 'JPY',
		number: '392',
		digits: 0,
		currency: 'Yen',
		countries: ['JPN'],
	},
	{
		code: 'KES',
		number: '404',
		digits: 2,
		currency: 'Kenyan Shilling',
		countries: ['KEN'],
	},
	{
		code: 'KGS',
		number: '417',
		digits: 2,
		currency: 'Som',
		countries: ['KGZ'],
	},
	{
		code: 'KHR',
		number: '116',
		digits: 2,
		currency: 'Riel',
		countries: ['KHM'],
	},
	{
		code: 'KMF',
		number: '174',
		digits: 0,
		currency: 'Comorian Franc ',
		countries: ['COM'],
	},
	{
		code: 'KPW',
		number: '408',
		digits: 2,
		currency: 'North Korean Won',
		countries: ['PRK'],
	},
	{
		code: 'KRW',
		number: '410',
		digits: 0,
		currency: 'Won',
		countries: ['KOR'],
	},
	{
		code: 'KWD',
		number: '414',
		digits: 3,
		currency: 'Kuwaiti Dinar',
		countries: ['KWT'],
	},
	{
		code: 'KYD',
		number: '136',
		digits: 2,
		currency: 'Cayman Islands Dollar',
		countries: ['CYM'],
	},
	{
		code: 'KZT',
		number: '398',
		digits: 2,
		currency: 'Tenge',
		countries: ['KAZ'],
	},
	{
		code: 'LAK',
		number: '418',
		digits: 2,
		currency: 'Lao Kip',
		countries: ['LAO'],
	},
	{
		code: 'LBP',
		number: '422',
		digits: 2,
		currency: 'Lebanese Pound',
		countries: ['LBN'],
	},
	{
		code: 'LKR',
		number: '144',
		digits: 2,
		currency: 'Sri Lanka Rupee',
		countries: ['LKA'],
	},
	{
		code: 'LRD',
		number: '430',
		digits: 2,
		currency: 'Liberian Dollar',
		countries: ['LBR'],
	},
	{
		code: 'LSL',
		number: '426',
		digits: 2,
		currency: 'Loti',
		countries: ['LSO'],
	},
	{
		code: 'LYD',
		number: '434',
		digits: 3,
		currency: 'Libyan Dinar',
		countries: ['LBY'],
	},
	{
		code: 'MAD',
		number: '504',
		digits: 2,
		currency: 'Moroccan Dirham',
		countries: ['MAR', 'ESH'],
	},
	{
		code: 'MDL',
		number: '498',
		digits: 2,
		currency: 'Moldovan Leu',
		countries: ['MDA'],
	},
	{
		code: 'MGA',
		number: '969',
		digits: 2,
		currency: 'Malagasy Ariary',
		countries: ['MDG'],
	},
	{
		code: 'MKD',
		number: '807',
		digits: 2,
		currency: 'Denar',
		countries: ['MKD'],
	},
	{
		code: 'MMK',
		number: '104',
		digits: 2,
		currency: 'Kyat',
		countries: ['MMR'],
	},
	{
		code: 'MNT',
		number: '496',
		digits: 2,
		currency: 'Tugrik',
		countries: ['MNG'],
	},
	{
		code: 'MOP',
		number: '446',
		digits: 2,
		currency: 'Pataca',
		countries: ['MAC'],
	},
	{
		code: 'MRU',
		number: '929',
		digits: 2,
		currency: 'Ouguiya',
		countries: ['MRT'],
	},
	{
		code: 'MUR',
		number: '480',
		digits: 2,
		currency: 'Mauritius Rupee',
		countries: ['MUS'],
	},
	{
		code: 'MVR',
		number: '462',
		digits: 2,
		currency: 'Rufiyaa',
		countries: ['MDV'],
	},
	{
		code: 'MWK',
		number: '454',
		digits: 2,
		currency: 'Malawi Kwacha',
		countries: ['MWZ'],
	},
	{
		code: 'MXN',
		number: '484',
		digits: 2,
		currency: 'Mexican Peso',
		countries: ['MEX'],
	},
	{
		code: 'MXV',
		number: '979',
		digits: 2,
		currency: 'Mexican Unidad de Inversion (UDI)',
		countries: ['MEX'],
	},
	{
		code: 'MYR',
		number: '458',
		digits: 2,
		currency: 'Malaysian Ringgit',
		countries: ['MYS'],
	},
	{
		code: 'MZN',
		number: '943',
		digits: 2,
		currency: 'Mozambique Metical',
		countries: ['MOZ'],
	},
	{
		code: 'NAD',
		number: '516',
		digits: 2,
		currency: 'Namibia Dollar',
		countries: ['NAM'],
	},
	{
		code: 'NGN',
		number: '566',
		digits: 2,
		currency: 'Naira',
		countries: ['NGA'],
	},
	{
		code: 'NIO',
		number: '558',
		digits: 2,
		currency: 'Cordoba Oro',
		countries: ['NIC'],
	},
	{
		code: 'NOK',
		number: '578',
		digits: 2,
		currency: 'Norwegian Krone',
		countries: ['BVT', 'NOR', 'SJM'],
	},
	{
		code: 'NPR',
		number: '524',
		digits: 2,
		currency: 'Nepalese Rupee',
		countries: ['NPL'],
	},
	{
		code: 'NZD',
		number: '554',
		digits: 2,
		currency: 'New Zealand Dollar',
		countries: ['COK', 'NZL', 'NIU', 'PCN', 'TKL'],
	},
	{
		code: 'OMR',
		number: '512',
		digits: 3,
		currency: 'Rial Omani',
		countries: ['OMN'],
	},
	{
		code: 'PAB',
		number: '590',
		digits: 2,
		currency: 'Balboa',
		countries: ['PAN'],
	},
	{
		code: 'PEN',
		number: '604',
		digits: 2,
		currency: 'Sol',
		countries: ['PER'],
	},
	{
		code: 'PGK',
		number: '598',
		digits: 2,
		currency: 'Kina',
		countries: ['PNG'],
	},
	{
		code: 'PHP',
		number: '608',
		digits: 2,
		currency: 'Philippine Peso',
		countries: ['PHL'],
	},
	{
		code: 'PKR',
		number: '586',
		digits: 2,
		currency: 'Pakistan Rupee',
		countries: ['PAK'],
	},
	{
		code: 'PLN',
		number: '985',
		digits: 2,
		currency: 'Zloty',
		countries: ['POL'],
	},
	{
		code: 'PYG',
		number: '600',
		digits: 0,
		currency: 'Guarani',
		countries: ['PRY'],
	},
	{
		code: 'QAR',
		number: '634',
		digits: 2,
		currency: 'Qatari Rial',
		countries: ['QAT'],
	},
	{
		code: 'RON',
		number: '946',
		digits: 2,
		currency: 'Romanian Leu',
		countries: ['ROU'],
	},
	{
		code: 'RSD',
		number: '941',
		digits: 2,
		currency: 'Serbian Dinar',
		countries: ['SRB'],
	},
	{
		code: 'RUB',
		number: '643',
		digits: 2,
		currency: 'Russian Ruble',
		countries: ['RUS'],
	},
	{
		code: 'RWF',
		number: '646',
		digits: 0,
		currency: 'Rwanda Franc',
		countries: ['RWA'],
	},
	{
		code: 'SAR',
		number: '682',
		digits: 2,
		currency: 'Saudi Riyal',
		countries: ['SAU'],
	},
	{
		code: 'SBD',
		number: '090',
		digits: 2,
		currency: 'Solomon Islands Dollar',
		countries: ['SLB'],
	},
	{
		code: 'SCR',
		number: '690',
		digits: 2,
		currency: 'Seychelles Rupee',
		countries: ['SYC'],
	},
	{
		code: 'SDG',
		number: '938',
		digits: 2,
		currency: 'Sudanese Pound',
		countries: ['SDN'],
	},
	{
		code: 'SEK',
		number: '752',
		digits: 2,
		currency: 'Swedish Krona',
		countries: ['SWE'],
	},
	{
		code: 'SGD',
		number: '702',
		digits: 2,
		currency: 'Singapore Dollar',
		countries: ['SGP'],
	},
	{
		code: 'SHP',
		number: '654',
		digits: 2,
		currency: 'Saint Helena Pound',
		countries: ['SHN', 'ASC', 'TRC'],
	},
	{
		code: 'SLE',
		number: '925',
		digits: 2,
		currency: 'Leone',
		countries: ['SLE'],
	},
	{
		code: 'SOS',
		number: '706',
		digits: 2,
		currency: 'Somali Shilling',
		countries: ['SOM'],
	},
	{
		code: 'SRD',
		number: '968',
		digits: 2,
		currency: 'Surinam Dollar',
		countries: ['SUR'],
	},
	{
		code: 'SSP',
		number: '728',
		digits: 2,
		currency: 'South Sudanese Pound',
		countries: ['SSD'],
	},
	{
		code: 'STN',
		number: '930',
		digits: 2,
		currency: 'Dobra',
		countries: ['STP'],
	},
	{
		code: 'SVC',
		number: '222',
		digits: 2,
		currency: 'El Salvador Colon',
		countries: ['SLV'],
	},
	{
		code: 'SYP',
		number: '760',
		digits: 2,
		currency: 'Syrian Pound',
		countries: ['SYR'],
	},
	{
		code: 'SZL',
		number: '748',
		digits: 2,
		currency: 'Lilangeni',
		countries: ['SWZ'],
	},
	{
		code: 'THB',
		number: '764',
		digits: 2,
		currency: 'Baht',
		countries: ['THA'],
	},
	{
		code: 'TJS',
		number: '972',
		digits: 2,
		currency: 'Somoni',
		countries: ['TJK'],
	},
	{
		code: 'TMT',
		number: '934',
		digits: 2,
		currency: 'Turkmenistan New Manat',
		countries: ['TKM'],
	},
	{
		code: 'TND',
		number: '788',
		digits: 3,
		currency: 'Tunisian Dinar',
		countries: ['TUN'],
	},
	{
		code: 'TOP',
		number: '776',
		digits: 2,
		currency: 'Pa’anga',
		countries: ['TON'],
	},
	{
		code: 'TRY',
		number: '949',
		digits: 2,
		currency: 'Turkish Lira',
		countries: ['TUR'],
	},
	{
		code: 'TTD',
		number: '780',
		digits: 2,
		currency: 'Trinidad and Tobago Dollar',
		countries: ['TTO'],
	},
	{
		code: 'TWD',
		number: '901',
		digits: 2,
		currency: 'New Taiwan Dollar',
		countries: ['TWN'],
	},
	{
		code: 'TZS',
		number: '834',
		digits: 2,
		currency: 'Tanzanian Shilling',
		countries: ['TZA'],
	},
	{
		code: 'UAH',
		number: '980',
		digits: 2,
		currency: 'Hryvnia',
		countries: ['UKR'],
	},
	{
		code: 'UGX',
		number: '800',
		digits: 0,
		currency: 'Uganda Shilling',
		countries: ['UGA'],
	},
	{
		code: 'USD',
		number: '840',
		digits: 2,
		currency: 'US Dollar',
		countries: [
			'ASM',
			'BES',
			'IOT',
			'ECU',
			'SLV',
			'GUM',
			'HTI',
			'MHL',
			'FSM',
			'MNP',
			'PLW',
			'PAN',
			'PRI',
			'TLS',
			'TCA',
			'UMI',
			'USA',
			'VGB',
			'VIR',
		],
	},
	{
		code: 'USN',
		number: '997',
		digits: 2,
		currency: 'US Dollar (Next day)',
		countries: ['USA'],
	},
	{
		code: 'UYI',
		number: '940',
		digits: 0,
		currency: 'Uruguay Peso en Unidades Indexadas (UI)',
		countries: ['URY'],
	},
	{
		code: 'UYU',
		number: '858',
		digits: 2,
		currency: 'Peso Uruguayo',
		countries: ['URY'],
	},
	{
		code: 'UYW',
		number: '927',
		digits: 4,
		currency: 'Unidad Previsional',
		countries: ['URY'],
	},
	{
		code: 'UZS',
		number: '860',
		digits: 2,
		currency: 'Uzbekistan Sum',
		countries: ['UZB'],
	},
	{
		code: 'VED',
		number: '926',
		digits: 2,
		currency: 'Bolívar Soberano',
		countries: ['VEN'],
	},
	{
		code: 'VES',
		number: '928',
		digits: 2,
		currency: 'Bolívar Soberano',
		countries: ['VEN'],
	},
	{
		code: 'VND',
		number: '704',
		digits: 0,
		currency: 'Dong',
		countries: ['VNM'],
	},
	{
		code: 'VUV',
		number: '548',
		digits: 0,
		currency: 'Vatu',
		countries: ['VUT'],
	},
	{
		code: 'WST',
		number: '882',
		digits: 2,
		currency: 'Tala',
		countries: ['WSM'],
	},
	{
		code: 'XAF',
		number: '950',
		digits: 0,
		currency: 'CFA Franc BEAC',
		countries: ['CMR', 'CAF', 'TCD', 'COG', 'GNQ', 'GAB'],
	},
	{
		code: 'XCD',
		number: '951',
		digits: 2,
		currency: 'East Caribbean Dollar',
		countries: ['ANG', 'ANT', 'DOM', 'GRD', 'MTQ', 'KNA', 'LCA', 'VCT'],
	},
	{
		code: 'XDR',
		number: '960',
		digits: 0,
		currency: 'SDR (Special Drawing Right)',
		countries: ['IMF'],
	},
	{
		code: 'XOF',
		number: '952',
		digits: 0,
		currency: 'CFA Franc BCEAO',
		countries: ['BEN', 'BFA', 'CIV', 'GNB', 'MLI', 'NER', 'SEN', 'TGO'],
	},
	{
		code: 'XPF',
		number: '953',
		digits: 0,
		currency: 'CFP Franc',
		countries: ['PYF', 'NCL', 'WLF'],
	},
	{
		code: 'XSU',
		number: '994',
		digits: 0,
		currency: 'Sucre',
		countries: ['SUCRE'],
	},
	{
		code: 'XUA',
		number: '965',
		digits: 0,
		currency: 'ADB Unit of Account',
		countries: ['ADB'],
	},
	{
		code: 'YER',
		number: '886',
		digits: 2,
		currency: 'Yemeni Rial',
		countries: ['YEM'],
	},
	{
		code: 'ZAR',
		number: '710',
		digits: 2,
		currency: 'Rand',
		countries: ['LSO', 'NAM', 'ZAF'],
	},
	{
		code: 'ZMW',
		number: '967',
		digits: 2,
		currency: 'Zambian Kwacha',
		countries: ['ZMB'],
	},
	{
		code: 'ZWG',
		number: '924',
		digits: 2,
		currency: 'Zimbabwe Gold',
		countries: ['ZWE'],
	},
] as const

export type Currency = (typeof currencies)[number]
export type CurrencyCode = Currency['code']
export const currencyCodeSchema = z.custom<CurrencyCode>(
	(val) => currencies.find((c) => c.code === val)?.code,
)
export const getCurrency = (code: CurrencyCode) =>
	currencies.find((c) => c.code === code)

/**
 * How to display the currency in currency formatting.
 * Uses Intl.NumberFormat: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#currencydisplay
 */
export const currencyDisplaySchema = z.enum(['code', 'symbol'])

/**
 * All the ISO4217 currency codes.
 */
export const currencyCodes = currencies.map((c) => c.code) as [
	CurrencyCode,
	...CurrencyCode[],
]
