import {drizzleZeroConfig} from 'drizzle-zero';
import * as drizzleSchema from '../db/drizzle/schema';

export * from '@drizzle-zero/db/types';

export const schema = drizzleZeroConfig(drizzleSchema, {
  tables: {
    allTypes: true,
    analyticsDashboard: true,
    analyticsWidget: true,
    analyticsWidgetQuery: true,
    benefitEnrollment: true,
    benefitPlan: true,
    billingInvoice: true,
    billingInvoiceLine: true,
    budget: true,
    budgetLine: true,
    crmAccount: true,
    crmActivity: true,
    crmActivityType: true,
    crmContact: true,
    crmNote: true,
    crmOpportunity: true,
    crmOpportunityStageHistory: true,
    crmPipelineStage: true,
    department: true,
    documentFile: true,
    documentFileVersion: true,
    documentFolder: true,
    documentLibrary: true,
    documentSharing: true,
    employeeDocument: true,
    employeeProfile: true,
    employmentHistory: true,
    expenseItem: true,
    expenseReport: true,
    filters: true,
    friendship: true,
    integrationCredential: true,
    integrationEvent: true,
    integrationWebhook: true,
    inventoryItem: true,
    inventoryLevel: true,
    inventoryLocation: true,
    ledgerAccount: true,
    ledgerEntry: true,
    ledgerTransaction: true,
    marketingAudience: true,
    marketingCampaign: true,
    marketingCampaignAudience: true,
    marketingCampaignChannel: true,
    marketingChannel: true,
    medium: true,
    message: true,
    omittedTable: true,
    orderItem: true,
    orderPayment: true,
    orderTable: true,
    payment: true,
    product: true,
    productCategory: true,
    productMedia: true,
    productVariant: true,
    project: true,
    projectAssignment: true,
    projectAttachment: true,
    projectAudit: true,
    projectComment: true,
    projectNote: true,
    projectPhase: true,
    projectTag: true,
    projectTask: true,
    projectTaskTag: true,
    shipment: true,
    shipmentItem: true,
    supportTicket: true,
    supportTicketAssignment: true,
    supportTicketAudit: true,
    supportTicketMessage: true,
    supportTicketTag: true,
    supportTicketTagLink: true,
    team: true,
    timeEntry: true,
    timesheet: true,
    user: true,

    testSerialPk: true,
    testBigSerialPk: true,
    testUuidPk: true,
    testUuidSqlDefaultPk: true,
    testTextDefaultPk: true,
    testTimestampDefaultPk: true,
    testIntegerDefaultPk: true,
    testCompositePkBothDefaults: true,
    testCompositePkOneDefault: true,
  },
});
